### ISSUE TITLE
Proper Deno Import?

### ISSUE THREAD

**Issue by tmikaeld** [invertase/denque#39]
Any chance we can get a proper module for Deno?

```
error: TS2596 [ERROR]: 'Denque' can only be imported by turning on the 'esModuleInterop' flag and using a default import.
import { Denque } from "https://deno.land/x/denque@v2.0.1/index.js";
         ~~~~~~
    at file:///home/thomas/tamio/renderer/server.ts:3:10

TS2497 [ERROR]: This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.
import { Denque } from "https://deno.land/x/denque@v2.0.1/index.js";
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/thomas/tamio/renderer/server.ts:3:24

Found 2 errors.
```

**Comment by Salakar** [comment]
I'm not super familiar with Deno but I would accept PRs for this

**Comment by tmikaeld** [comment]
I've just started using it myself, but I can see if I can figure it out, thanks!
